[project]
name = "mp3-player-rpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mia Weingart", email = "weingart.mia@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gpiozero>=2.0.1.post3",
    "pillow>=12.3.0",
]

[project.scripts]
mp3-player-rpi = "mp3_player_rpi:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
